Update post-land.yml

diff --git a/.github/workflows/post-land.yml b/.github/workflows/post-land.yml
--- a/.github/workflows/post-land.yml
+++ b/.github/workflows/post-land.yml
@@ -1,76 +1,164 @@
----
-name: Post-land Test
+name: ci-post-land
 
 on:
   push:
-    branches:
-      - 'release**'
+    branches: [ harisharavindan-patch-1 ] # "gha-test-*"
+
+defaults:
+  run:
+    shell: bash
+
+env:
+  max_threads: 16
+  pre_command: cd /opt/git/diem/
 
 jobs:
-  run-cluster-test-pre-release-suite:
-    name: Run the pre-release suite of Cluster Test
-    runs-on: self-hosted
-    # The pre-release suite run time varies 1~1.5 hr.
-    timeout-minutes: 120
+  prepare:
+    runs-on: ubuntu-latest
+    outputs:
+      changes-target-branch: ${{ steps.changes.outputs.changes-target-branch }}
+      changes-base-git-rev: ${{ steps.changes.outputs.changes-base-git-rev }}
+      changes-base-githash: ${{ steps.changes.outputs.changes-base-githash }}
+      changes-pull-request-number: ${{ steps.changes.outputs.changes-pull-request-number }}
+      rust-changes: ${{ steps.rust-changes.outputs.changes-found }}
+      base-image-changes: ${{ steps.base-image-changes.outputs.changes-found }}
+      update-osx-sccache: ${{ steps.environment.outputs.name }}
     steps:
-      - uses: actions/checkout@v1
-      - name: set_env
-        id: set_env
+      - uses: actions/checkout@v2.3.4
+        with:
+          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
+          # On `push` this value will be empty and will "do-the-right-thing"
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0 #get all the history!!!
+      - name: Git Hooks and Checks
+        run: ./scripts/git-checks.sh
+      - id: changes
+        name: determine changes
+        uses: diem/actions/changes@faadd16607b77dfa2231a8f366883e01717b3225
+        with:
+          workflow-file: ci-post-land.yml
+          github-token: ${{secrets.GITHUB_TOKEN}}
+      - id: rust-changes
+        name: find rust/cargo changes.
+        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        with:
+          pattern: '^documentation\|^docker\|^scripts\|^developers.diem.com'
+          invert: "true"
+      - id: base-image-changes
+        name: find dev-setup.sh/base docker image changes
+        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        with:
+          pattern: '.github/workflows/ci-post-land.yml\|.github/actions/dockerhub_login/action.yml\|docker/ci/github/Dockerfile\|scripts/dev_setup.sh\|rust-toolchain'
+
+  build_ci_base_docker_image:
+    needs: prepare
+    runs-on: testnet-runner-ubuntu
+    # if: ${{ needs.prepare.outputs.base-image-changes == 'true' && github.event_name == 'push' }}
+    # continue-on-error: false,
+    env:
+      DOCKERHUB_ORG: diem
+    environment:
+      name: Docker
+      url: https://hub.docker.com/u/diem
+    steps:
+      - uses: actions/checkout@v2.3.4
+        with:
+          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
+          # On `push` this value will be empty and will "do-the-right-thing"
+          ref: ${{ github.event.pull_request.head.sha }}
+          fetch-depth: 0 #get all the history!!!
+      - name: Git Hooks and Checks
+        run: ./scripts/git-checks.sh
+      - name: build image
+        run: docker build -f docker/ci/github/Dockerfile -t ${{ env.DOCKERHUB_ORG }}/build_environment:${{ needs.prepare.outputs.changes-target-branch }} .
+      - name: Sign in to dockerhub, install image signing cert.
+        uses: ./.github/actions/dockerhub_login
+        with:
+          username: ${{ secrets.ENV_DOCKERHUB_USERNAME }}
+          password: ${{ secrets.ENV_DOCKERHUB_PASSWORD }}
+          key_material: ${{ secrets.ENV_DOCKERHUB_KEY_MATERIAL }}
+          key_name: ${{ secrets.ENV_DOCKERHUB_KEY_NAME }}
+          key_password: ${{ secrets.ENV_DOCKERHUB_KEY_PASSWORD }}
+      - name: Push to dockerhub.
         run: |
-          HEAD_GIT_REV=$(git rev-parse --short=8 HEAD)
-          echo "HEAD_GIT_REV=$HEAD_GIT_REV" >> $GITHUB_ENV
-          IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})_$HEAD_GIT_REV
-          echo $IMAGE_TAG
-          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
-      - name: poll_images
-        # Poll until images are ready
-        env:
-          AWS_REGION: us-west-2
-          RETRIES: 30
-        run: |
-          set +e
-          retry=0
-          status=1
-          while [[ $status != 0 && $retry -lt $RETRIES ]]; do
-            status=0
-            for image in diem/validator diem/validator_tcb diem/init diem/cluster_test; do
-              aws ecr describe-images --region $AWS_REGION --repository-name $image --image-ids=imageTag=$IMAGE_TAG
-              status=$((status + $?))
-            done
-            retry=$((retry + 1))
-            if [[ $status != 0 ]] ; then
-              echo "CI has not pushed all images to ECR."
-              echo "Wait $((1*$retry)) of $((1*$RETRIES)) minutes before retry."
-              sleep 1m
+          if [[ "$DOCKERHUB_LOGGED_IN" == true ]]; then
+            disable_content_trust=true
+            if [[ "$DOCKERHUB_CAN_SIGN" == true ]]; then
+              disable_content_trust=false
             fi
-          done
-          exit $status
-      - name: Run Cluster Test
+            docker push --disable-content-trust=${disable_content_trust} ${{ env.DOCKERHUB_ORG }}/build_environment:${{ needs.prepare.outputs.changes-target-branch }}
+          fi
+        env:
+          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.ENV_DOCKERHUB_KEY_PASSWORD }}
+
+  build-release-images:
+    needs: prepare
+    runs-on: testnet-runner-ubuntu
+    # continue-on-error: false
+    env:
+      TAG: github-1
+      CHANGES_TARGET_BRANCH: release-1.1
+    environment:
+      name: Docker
+      url: https://hub.docker.com/u/diem
+    steps:
+      - uses: actions/checkout@v2.3.4
+        with:
+          fetch-depth: 0 #get all the history!!!
+      - name: Sign in to dockerhub, install image signing cert.
+        uses: ./.github/actions/dockerhub_login
+        with:
+          username: ${{ secrets.ENV_DOCKERHUB_USERNAME }}
+          password: ${{ secrets.ENV_DOCKERHUB_PASSWORD }}
+          key_material: ${{ secrets.ENV_DOCKERHUB_KEY_MATERIAL }}
+          key_name: ${{ secrets.ENV_DOCKERHUB_KEY_NAME }}
+          key_password: ${{ secrets.ENV_DOCKERHUB_KEY_PASSWORD }}
+      - name: should pre build docker images (targeting a release branch)?
+        if: ${{ github.ref == 'refs/heads/auto' }}
         run: |
-          date
-          BASE_GIT_REV=$(git rev-parse $HEAD_GIT_REV^)
-          ./scripts/cti --tag $IMAGE_TAG --timeout-secs 7200 \
-            --env SLACK_CHANGELOG_URL=${{ secrets.WEBHOOK_CHANGELOG }} \
-            --changelog $BASE_GIT_REV $HEAD_GIT_REV \
-            --suite pre_release
-      - name: Push alert
-        if: ${{ failure() }}
+          if  [[ ! "$CHANGES_TARGET_BRANCH" =~ "^release-[0-9|.]+$" ]] && [[ ! "$CHANGES_TARGET_BRANCH" =~ "^gha-test-[0-9|.]+$" ]] ; then
+            echo Targeting branch $CHANGES_TARGET_BRANCH will not pre-publish docker images.
+          fi
+      - name: pre-release docker images
+        if: ${{ github.ref == 'refs/heads/auto' }}
         run: |
-          jq -n \
-            --arg msg "*${{ github.job }}* job in ${{ github.workflow }} workflow failed with $IMAGE_TAG." \
-            --arg url "https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}" \
-            '{
-              "attachments": [
-                {
-                  "text": $msg,
-                  "actions": [
-                    {
-                      "type": "button",
-                      "text": "Visit Job",
-                      "url": $url
-                    }
-                  ]
-                }
-              ]
-            }' > /tmp/payload
-          curl -X POST -H 'Content-type: application/json' -d @/tmp/payload ${{ secrets.WEBHOOK_PUSH }}
+          BRANCH="$CHANGES_TARGET_BRANCH"
+          success=0
+          tmpfile=$(mktemp)
+          echo "Failed to push:" > "${tmpfile}"
+          docker/build_push.sh -u -p -b ${BRANCH} -n client || success=$(echo "client" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n init || success=$(echo "init" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n faucet || success=$(echo "faucet" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n tools || success=$(echo "tools" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n validator || success=$(echo "validator" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n validator-tcb || success=$(echo "validator-tcb" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -p -b ${BRANCH} -n cluster-test || success=$(echo "cluster-test" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n forge || success=$(echo "forge" >> "${tmpfile}"; echo 1)
+          if [[ "$success" == "1" ]]; then
+            cat "${tmpfile}"
+          fi
+          exit $success
+        env:
+          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.ENV_DOCKERHUB_KEY_PASSWORD }}
+      - name: pull pre images (or build if not pullable) and push release docker images if not on auto branch.
+        if: ${{ github.ref != 'refs/heads/auto' }}
+        run: |
+          set -x
+          BRANCH=$(echo "release-1.1" )
+          success=0
+          tmpfile=$(mktemp)
+          echo "Failed to push:" >> "${tmpfile}"
+          docker/build_push.sh -u -b ${BRANCH} -n client || success=$(echo "client" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n init ||  success=$(echo "init" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n faucet ||  success=$(echo "faucet" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n tools ||  success=$(echo "tools" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n validator || success=$(echo "validator" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n validator-tcb || success=$(echo "validator-tcb" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n cluster-test || success=$(echo "cluster-test" >> "${tmpfile}"; echo 1)
+          docker/build_push.sh -u -b ${BRANCH} -n forge || success=$(echo "forge" >> "${tmpfile}"; echo 1)
+          if [[ "$success" == "1" ]]; then
+            cat "${tmpfile}"
+          fi
+          exit $success
+        env:
+          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.ENV_DOCKERHUB_KEY_PASSWORD }}
